name: Anchore Scan
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Set up JDK 11
              uses: actions/setup-java@v3
              with:
                java-version: '11'
                distribution: 'temurin'
            - name: Build with Maven
              run: mvn --batch-mode --update-snapshots package
            - name: Docker Build
              run: docker build . --file Dockerfile --tag testimage
            - uses: anchore/scan-action@v2
              with:
                  image-reference: "testimage"
                  dockerfile-path: "./Dockerfile"
                  fail-build: true
