
name: 'JFrog CI Container Scan'
on: [push]
jobs:
 jfrog-ci-integration:
   runs-on: ubuntu-latest
   env:
     JF_ARTIFACTORY_1: ${{ secrets.JF_ARTIFACTORY_SECRET_1 }}
     JFROG_BUILD_STATUS: PASS
   steps:
     - name: Checkout
       uses: actions/checkout@v2
     - name: Setup JFrog CLI
       uses: jfrog/setup-jfrog-cli@v3
     - name: Check JFrog CLI Version
       run: jf --version
     - name: Set up JDK 11
       uses: actions/setup-java@v2
       with:
         java-version: '11'
         distribution: 'temurin'
     - name: Build with Maven
       run: mvn --batch-mode --update-snapshots package
     - name: Build a Docker image
       run: docker build -t snapshot-image .
     - name: Scan Docker image
       run: |
         jf docker scan snapshot-image:latest
         # Scan the published build-info with Xray
         jfrog rt bs
