name: 'Trivy Scan'
on:
  push:
    branches:
      - main
jobs:
  build:
    name: 'trivy scan'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Run Trivy vulnerability scanner in IaC mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scanners: 'vuln,config,secret'
          exit-code: '1'
          ignore-unfixed: true
